#!/usr/bin/env bash
# Copyright (c) 2023 rM-self-serve
# SPDX-License-Identifier: MIT

main() {
	# collect options before or after command
	no_prompt=false
	if nop_match "$1"; then
		no_prompt=true
		shift
	fi
	cmd=("$1")
	if [[ "$2" != "" ]]; then
		shift
		if [ "$no_prompt" == false ] && nop_match "$1"; then
			no_prompt=true
			shift
		fi
		cmd+=("$@")
	fi

	case ${cmd[@]} in
	'-h' | '--help' | '')
		cli_info
		;;
	'apply')
		apply
		;;
	'revert')
		revert
		;;
	*)
		echo 'input not recognized'
		cli_info
		;;
	esac
	true
}

nop_match() {
	[[ "$1" == *"-y"* ]] || [[ "$1" == *"--no-prompt"* ]]
}

cli_info() {
	echo 'This program will add an upload button to the web interface.'
	echo 'Included funtionality to revert modification.'
	echo 'Source+Docs: https://github.com/rM-self-serve/webinterface-upload-button'
	echo ''
	echo -e "${CYAN}USAGE:${NC}"
	echo '  webint-upldbtn [OPTIONS] [COMMANDS]'
	echo ''
	echo -e "${CYAN}COMMANDS:${NC}"
	echo '  apply           Apply upload button modification'
	echo '  revert          Revert upload button modification'
	echo ''
	echo -e "${CYAN}OPTIONS:${NC}"
	echo '  -y, --no-promt  Do not show confirmation prompt'
	echo '  -h, --help      Show help'
}

vars() {
	webui_dir='/usr/share/remarkable/webui'
	index_file="${webui_dir}/index.html"
	ndx_content=$(cat $index_file)

	no_wspc_html=$(
		printf '
		<!-- lines added by webint-upldbtn (cli will not recognize if edited) -->
		<form method=post enctype=multipart/form-data action=upload>
			<input type=file name=file>
			<input type=submit value=Upload>
		</form>
		<!-- end webint-upldbtn -->' |
			tr -d "\n" | tr -d "\t"
	)
	sed_wspc_html=${no_wspc_html//[\/]/\\\/}

	css_file="${webui_dir}/$(echo "$ndx_content" | xargs -n 1 | grep -oE 'app-.+\.css')"
	css_content=$(tr -d '\n' <"$css_file")

	unmod_css='.list{position:fixed;width:70%;top:70px;bottom:0'
	moded_css='.list{position:fixed;width:70%;top:94px;bottom:0'
}

is_html_moded() {
	[[ "$ndx_content" == *"$no_wspc_html"* ]]
}

can_mod_html() {
	echo "$ndx_content" | grep -qh '<body>'
}

is_css_moded() {
	echo "$css_content" | grep -qh "$moded_css"
}

can_mod_css() {
	echo "$css_content" | grep -qh "$unmod_css"
}

prompt() {
	if [ "$no_prompt" = false ]; then
		read -r -p "Would you like to continue? [y/N] " response
		case "$response" in
		[yY][eE][sS] | [yY])
			true
			;;
		*)
			echo "Cancel"
			exit
			;;
		esac
	fi
}

apply() {
	vars

	echo "Applying webint-upldbtn will edit:"
	echo "$index_file"
	echo "$css_file"
	echo ""
	prompt

	apply_index
	apply_css
}

apply_index() {
	if is_html_moded; then
		echo "Html already modified"
		return
	fi
	if ! can_mod_html; then
		echo "Html unrecognized"
		return
	fi

	sed -i "s/<body>/<body>$sed_wspc_html/" "$index_file"

	echo "Html modified"
}

revert() {
	vars

	echo "Reverting webint-upldbtn will edit:"
	echo "$index_file"
	echo "$css_file"
	echo ""
	prompt

	revert_index
	revert_css
}

revert_index() {

	if ! is_html_moded; then
		echo "Html has not been modified"
		return
	fi

	sed -i "s/$sed_wspc_html//g" "$index_file"

	echo "Html reverted"
}

apply_css() {
	if ! can_mod_css; then
		if is_css_moded; then
			echo "Css already modified"
		else
			echo "Css is not recognized"
		fi
		return
	fi

	sed -i "s/${unmod_css}/${moded_css}/" "$css_file"
	echo "Css modified"
}

revert_css() {
	if ! is_css_moded; then
		if can_mod_css; then
			echo "Css has not been modified"
		else
			echo "Css is not recognized"
		fi
		return
	fi

	sed -i \ "s/${moded_css}/${unmod_css}/" "$css_file"
	echo "Css reverted"
}

CYAN='\033[0;36m'
NC='\033[0m' # No Color

main "$@"
